from thesession.config import PATH_CACHE, PATH_FIG, PATH_FIG_DATA, PATH_MMSEQS
from thesession.viz import main_figs, si_figs
from thesession.pipeline.param_search import run_parameter_optimization
from thesession.pipeline.mmseqs import run_main_alignments
from thesession.pipeline.identification import data_for_identification
from thesession.pipeline.mutability import data_for_mutability
from thesession.pipeline.substitution import data_for_substitution
from thesession.pipeline.position import data_for_position
from thesession.pipeline.covariance import data_for_covariance
from thesession.pipeline.protein import data_for_protein_comparison


def make_figures():
    """Render all programmatic manuscript figures from cached FigureData/ into Figures/.

    Fig 1 is assembled manually (external compositing of ROC + tune-piano-roll
    sub-panels with hand-drawn illustrations) and is not regenerated here.
    """
    PATH_FIG.mkdir(parents=True, exist_ok=True)

    print("Fig 1 is assembled manually and is NOT regenerated by the pipeline.")
    print("  To rebuild its sub-panels: main_figs.plot_roc_curve() and, with a loaded")
    print("  `tunes` dict, main_figs.plot_example_tune(tunes).")

    # Fig 2, Fig 3 (fully programmatic)
    main_figs.fig2()
    main_figs.fig3()

    # Supporting figures
    si_figs.plot_optimization_scores()
    si_figs.plot_mutability_by_mode()
    si_figs.plot_submat_comparison()
    si_figs.plot_submat_corr()
    si_figs.plot_bar_pos_sub_rate_meters_dances()
    si_figs.plot_cov_rep_all_meters()


### Code for recreating the analyses in the paper.
### Creates and saves data for figures.
def main(redo=False):
    """
    Run the complete analysis pipeline, then render the figures.

    Runs each analysis stage in sequence (the manuscript has three main
    figures, but each analysis feeds several published panels, so the stages
    are named by analysis rather than by figure):

    * Identification: tune-family ROC curves (main Fig. 1).
    * Main alignments: shared prerequisite for every stage below.
    * Mutability: note prevalence, mutability, key-finding.
    * Substitution: note substitution distances.
    * Position: sequence-position effects.
    * Covariance: sequence covariance and repetition structure.

    Parameters
    ----------
    redo : bool, optional
        Passed to every sub-function.  If ``True``, all caches are
        invalidated and recomputed.  Default is ``False``.

    Returns
    -------
    None
    """
    # Ensure top-level output directories exist
    for path in [PATH_MMSEQS, PATH_CACHE, PATH_FIG, PATH_FIG_DATA]:
        path.mkdir(parents=True, exist_ok=True)

    print("=== Protein comparison data ===")
    data_for_protein_comparison(redo=redo)

    print("\n=== Parameter optimisation ===")
    run_parameter_optimization(redo=redo)

    print("\n=== Identification: similar-tune ROC (Fig. 1) ===")
    data_for_identification(redo=redo)

    print("\n=== Main alignments (shared prerequisite) ===")
    df, tunes, df_parts, parts_data, res, res0, mismatches = run_main_alignments(redo=redo)

    print("\n=== Mutability: prevalence, mutability, key-finding ===")
    data_for_mutability(df, tunes, df_parts, parts_data, res, res0, mismatches, redo=redo)

    print("\n=== Substitution: note substitution distances ===")
    data_for_substitution(df, tunes, df_parts, parts_data, res, res0, mismatches, redo=redo)

    print("\n=== Position: sequence-position effects ===")
    data_for_position(df, tunes, df_parts, parts_data, res, res0, mismatches, redo=redo)

    print("\n=== Covariance: position covariance and repetition ===")
    data_for_covariance(res0, parts_data, redo=redo)

    print("\n=== Rendering figures ===")
    make_figures()


if __name__ == "__main__":

    main(redo=False)
