from thesession.config import PATH_CACHE, PATH_FIG, PATH_FIG_DATA, PATH_MMSEQS
from thesession.viz import main_figs, si_figs
from thesession.pipeline.param_search import run_parameter_optimization
from thesession.pipeline.fig1 import data_for_fig1
from thesession.pipeline.fig2 import run_main_alignments, data_for_fig2
from thesession.pipeline.fig3 import data_for_fig3
from thesession.pipeline.fig4 import data_for_fig4
from thesession.pipeline.fig5 import data_for_fig5
from thesession.pipeline.protein import data_for_protein_comparison


def make_figures():
    """Render all programmatic manuscript figures from cached FigureData/ into Figures/.

    Fig 1 is assembled manually (external compositing of ROC + tune-piano-roll
    sub-panels with hand-drawn illustrations) and is not regenerated here.
    """
    PATH_FIG.mkdir(parents=True, exist_ok=True)

    print("Fig 1 is assembled manually and is NOT regenerated by the pipeline.")
    print("  To rebuild its sub-panels: main_figs.plot_roc_curve() and, with a loaded")
    print("  `tunes` dict, main_figs.plot_example_tune(tunes).")

    # Fig 2, Fig 3 (fully programmatic)
    main_figs.fig2()
    main_figs.fig3()

    # Supporting figures
    si_figs.plot_optimization_scores()
    si_figs.plot_mutability_by_mode()
    si_figs.plot_submat_comparison()
    si_figs.plot_submat_corr()
    si_figs.plot_bar_pos_sub_rate_meters_dances()
    si_figs.plot_cov_rep_all_meters()


### Code for recreating the analyses in the paper.
### Creates and saves data for figures.
def main(redo=False):
    """
    Run the complete analysis pipeline for all figures.

    Calls each figure-data function in sequence:

    * Figure 1: tune-family identification ROC curves.
    * Main alignments: shared prerequisite for Figures 2–5.
    * Figure 2: note prevalence, mutability, key-finding.
    * Figure 3: note substitution distances.
    * Figure 4: sequence-position effects.
    * Figure 5: sequence covariance.

    Parameters
    ----------
    redo : bool, optional
        Passed to every sub-function.  If ``True``, all caches are
        invalidated and recomputed.  Default is ``False``.

    Returns
    -------
    None
    """
    # Ensure top-level output directories exist
    for path in [PATH_MMSEQS, PATH_CACHE, PATH_FIG, PATH_FIG_DATA]:
        path.mkdir(parents=True, exist_ok=True)

    print("=== Protein comparison data ===")
    data_for_protein_comparison(redo=redo)

    print("\n=== Parameter optimisation ===")
    run_parameter_optimization(redo=redo)

    print("\n=== Fig 1: Identifying similar tunes ===")
    data_for_fig1(redo=redo)

    print("\n=== Running main alignments ===")
    df, tunes, df_parts, parts_data, res, res0, mismatches = run_main_alignments(redo=redo)

    print("\n=== Fig 2: Note prevalence, mutability, key-finding ===")
    data_for_fig2(df, tunes, df_parts, parts_data, res, res0, mismatches, redo=redo)

    print("\n=== Fig 3: Note substitutions ===")
    data_for_fig3(df, tunes, df_parts, parts_data, res, res0, mismatches, redo=redo)

    print("\n=== Fig 4: Sequence position effects ===")
    data_for_fig4(df, tunes, df_parts, parts_data, res, res0, mismatches, redo=redo)

    print("\n=== Fig 5: Sequence covariance ===")
    data_for_fig5(res0, parts_data, redo=redo)

    print("\n=== Rendering figures ===")
    make_figures()


if __name__ == "__main__":

    main(redo=False)
